AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  CommonStack:
    Type: String
    Description: 'Name of the stack for common resources'
    Default: ''
  OpenAPISecretArn:
    Type: String
    Default: ''

Resources:
  GenerateVideoDescriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 600
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref OpenAPISecretArn

  GenerateVideoDescriptionStateMachine:
    Type: 'AWS::Serverless::StateMachine'
    Properties:
      DefinitionUri: statemachine/state-machine.asl.yml
      DefinitionSubstitutions:
        TranslateBucket:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-TranslateBucket'
        DescriptionBucketName:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-DescriptionBucket'
        NotificationTopic:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-NotificationTopicArn'
        GetSignedUrlFunction:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-GetSignedUrlFunction'
        GenerateVideoDescriptionFunction: !Ref GenerateVideoDescriptionFunction
      Tracing:
        Enabled: true
      Events:
        S3MediaTrigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - Fn::ImportValue:
                        'Fn::Sub': '${CommonStack}-TranslateBucket'
                object:
                  key: [{ prefix: 'test/' }] ## CHANGE LATER TO validated/ test/ so the endpoint doesnt get hit all the time
      Policies:
        - S3WritePolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-DescriptionBucket'
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-TranslateBucket'
        - S3WritePolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-TranslateBucket'
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-NotificationTopicArn'
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateVideoDescriptionFunction
        - LambdaInvokePolicy:
            FunctionName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-GetSignedUrlFunction'
        - CloudWatchPutMetricPolicy: {}
        - Version: 2012-10-17
          Statement:
            - Sid: XrayAccessPolicy
              Effect: Allow
              Action:
                - 'xray:PutTraceSegments'
                - 'xray:PutTelemetryRecords'
                - 'xray:GetSamplingRules'
                - 'xray:GetSamplingTargets'
                - 'xray:GetSamplingStatisticSummaries'
              Resource: '*'
