AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  NotificationTopicARN:
    Type: String
    Default: ''
  NotificationTopicName:
    Type: String
    Default: ''
  TranslateBucketName:
    Type: String
    Default: ''
  GetSignedURLFunctionName:
    Type: String
    Default: ''
  DescriptionBucketName:
    Type: String
    Default: ''
  OpenAPISecretArn:
    Type: String
    Default: ''

Resources:
  GenerateVideoDescriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 600
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref OpenAPISecretArn

  GenerateVideoDescriptionStateMachine:
    Type: 'AWS::Serverless::StateMachine'
    Properties:
      DefinitionUri: statemachine/state-machine.asl.yml
      DefinitionSubstitutions:
        TranslateBucket: !Ref TranslateBucketName
        DescriptionBucketName: !Ref DescriptionBucketName
        NotificationTopic: !Ref NotificationTopicARN
        GetSignedUrlFunction: !Ref GetSignedURLFunctionName
        GenerateVideoDescriptionFunction: !Ref GenerateVideoDescriptionFunction
      Tracing:
        Enabled: true
      Events:
        S3MediaTrigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - !Ref TranslateBucketName
                object:
                  key: [{ prefix: 'test/' }] ## CHANGE LATER TO validated/ test/ so the endpoint doesnt get hit all the time
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DescriptionBucketName
        - S3ReadPolicy:
            BucketName: !Ref TranslateBucketName
        - S3WritePolicy:
            BucketName: !Ref TranslateBucketName
        - SNSPublishMessagePolicy:
            TopicName: !Ref NotificationTopicName
        - LambdaInvokePolicy:
            FunctionName: !Ref GenerateVideoDescriptionFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GetSignedURLFunctionName
        - CloudWatchPutMetricPolicy: {}
        - Version: 2012-10-17
          Statement:
            - Sid: XrayAccessPolicy
              Effect: Allow
              Action:
                - 'xray:PutTraceSegments'
                - 'xray:PutTelemetryRecords'
                - 'xray:GetSamplingRules'
                - 'xray:GetSamplingTargets'
                - 'xray:GetSamplingStatisticSummaries'
              Resource: '*'
