AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  CommonStack:
    Type: String
    Description: 'Name of the stack for common resources'
    Default: ''
  FmpegLayerARN:
    Type: String
    Default: ''

Resources:
  ModifyVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.handler
      Runtime: nodejs16.x
      MemorySize: 10240
      Timeout: 600
      Layers:
        - !Ref FmpegLayerARN
      Environment:
        Variables:
          OriginalVideoBucketName:
            Fn::ImportValue:
              'Fn::Sub': '${CommonStack}-InputVideoBucket'
          DubbedAudioBucketName:
            Fn::ImportValue:
              'Fn::Sub': '${CommonStack}-AudioBucket'
          ResultBucketName:
            Fn::ImportValue:
              'Fn::Sub': '${CommonStack}-DubbedBucket'
      Policies:
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-InputVideoBucket'
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-AudioBucket'
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-DubbedBucket'

  ##########################################################################
  #   STEP FUNCTION                                                        #
  ##########################################################################

  GetDubbedVideoStateMachine:
    Type: 'AWS::Serverless::StateMachine'
    Properties:
      DefinitionUri: statemachine/state-machine.asl.yml
      DefinitionSubstitutions:
        TranslateBucket:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-TranslateBucket'
        AudioTextBucket:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-AudioBucket'
        NotificationTopic:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-NotificationTopicArn'
        GetSignedUrlFunction:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-GetSignedUrlFunction'
        MakeVideoFunction: !Ref ModifyVideoFunction
        ResultBucketName:
          Fn::ImportValue:
            'Fn::Sub': '${CommonStack}-DubbedBucket'
      Tracing:
        Enabled: true
      Events:
        S3MediaTrigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - Fn::ImportValue:
                        'Fn::Sub': '${CommonStack}-TranslateBucket'
                object:
                  key: [{ prefix: 'validated/' }]
      Policies:
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-AudioBucket'
        - S3WritePolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-AudioBucket'
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-TranslateBucket'
        - S3WritePolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-TranslateBucket'
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-DubbedBucket'
        - S3WritePolicy:
            BucketName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-DubbedBucket'
        - SNSPublishMessagePolicy:
            TopicName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-NotificationTopicArn'
        - LambdaInvokePolicy:
            FunctionName: !Ref ModifyVideoFunction
        - LambdaInvokePolicy:
            FunctionName:
              Fn::ImportValue:
                'Fn::Sub': '${CommonStack}-GetSignedUrlFunction'
        - CloudWatchPutMetricPolicy: {}
        - Version: 2012-10-17
          Statement:
            - Sid: XrayAccessPolicy
              Effect: Allow
              Action:
                - 'xray:PutTraceSegments'
                - 'xray:PutTelemetryRecords'
                - 'xray:GetSamplingRules'
                - 'xray:GetSamplingTargets'
                - 'xray:GetSamplingStatisticSummaries'
              Resource: '*'
            - Sid: JobPolicy
              Effect: Allow
              Action:
                - 'polly:startSpeechSynthesisTask'
                - 'polly:getSpeechSynthesisTask'
              Resource: '*'
